### ISSUE TITLE
UI roadmap (1st pass)

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#4078]
# UI Roadmap (first pass)
This issue provides an overview of the things that need to be done, to move oldUI and newUI parts to dear-imgui.
See [project](https://github.com/pioneerspacesim/pioneer/projects/1?fullscreen=true)
[Mockup album.](http://imgur.com/a/6fqrd)
[Old mockups.](https://goo.gl/photos/usbRXT9TECbCPeNi8)

### Flight UI to imgui
- [x] Reticule
  - [x] Indicators
  - [x] Maneuver display
  - [x] Target data display
  - [x] Frame data display
  - [x] Orientation
  - [x] DeltaV display

- [x] cpanel removal
  - [x] Buttons
  - [x] Time accel
  - [x] Gauges (own)
  - [x] Gauges (target)
    - [x] Own data
    - [x] Target data (Targer scanner output)
    - [x] Hyperspace analyzer output
  - [x] Ground data
  - [x] Radar
    - [x] Planar (move it over to imgui?)
    - [x] Azimuthal
  - [x] Function buttons (ECM, etc)
  - [x] Missile selector 
  - [x] Alert display
### Comms UI to imgui
  - [x] Message log
  - [x] Autopilot commands (move to HUD?)
  - [x] Station list
### **[Sector map to imgui - In Progress](https://imgur.com/a/YuU79)**
  - [x] System data display (current, selected)
  - [x] Dispaly options toggles
  - [x] Search bar (+search radius, and list all found matches)
  - [x] Simple system list? (shows system closer than X ly)
  - [x] Hyperdrive stats display (range, fuel)
  - [x] Route planner
  - [x] ~~Better layout~~
### Orbital map to imgui
  - [x] Time controls and display (fwd, bwd, selected time point)
  - [x] Orbit planner controls
  - [x] Dipslay buttons/toggles (L-point, ship)
  - [x] Info box on bodies? (basic orbit data, starports)
  - [x] Mouse control tweak: Left Mouse focuses, Shift+Left Mouse selects? Or the other way. *Right now if you click, it selects and focuses, which isn't ideal, since sometimes your target is a child of a gas giant for example, and if you want to view your target, you first have to change it and change it back.*
### System overview to imgui
  - [x] Planet icons display
  - [x] Tabs
    - [x] Description, data. Population could go here too.
    - [x] ~~Trade info~~ (moved to SectorMap)

  
## NewUI to imgui
These UI parts actually aren't that bad, so maybe we might want to redesign them at first go?
### Main menu
  - [x] Game starts (3)
  - [x] Continue from last save
  - [x] Load / Save / (Delete?)
  - [x] Settings (and pause screen)
    - [x] Game settings
    - [x] Video settings
    - [x] Audio settings
    - [x] Controls
    - [x] Language
    - [x] In-game stuff (save, exit, return)
### Galaxy map to imgui
  - [x] ~~Zoom and scale info~~ (screen removed)
### Info screens (F3)
  Make it into a window?
  - [x] General info and ship spinner
    - [x] Ship naming
  - [x] Personal info
    - [x] Name and face changing
  - [x] Cargo hold (should be accessible from flight UI directly?)
    - [x] Refuel and pumpdown functions
    - [x] Jettison function
  - [x] Mission information
  - [x] Crew rooster
  - [x] Maybe a simple flight log where you could write notes?
### Station Screens
Make it into a window?
  - [x] Station lobby
    - [x] Refuel functions
    - [x] Launch function
  - [x] BBS
  - [x] Market
  - [x] Ship market
    - [x] Ship list
      - [x] Icons?
    - [x] Ship data
  - [x] Equipment market
    - [x] Equipment list
    - [x] List of installed equipment (/slots?)
    - [x] Mass data
  - [x] Repairs
  - [x] Police
### Misc
- [x] Move console to imgui

**Comment by kennworl** [comment]
That's quite a list.  :-)   Did you have more specific descriptions of the changes that you and ecraven are going to make?  I'm going through the process of designing the hardware console that is compatible with the controls in the imgui, and I would like to try and keep up with the planned gui changes, and be aware of any concept changes with the game (like adding new functions, controls, etc).  Nice job so far, by the way.  It's looking really slick.  I need to merge your gui changes into my repository and then get ecraven and the other devs to review it so it can be merged into the main trunk.  However, this list looks years long.  Maybe if I can get more of an idea what you are intending, I might have a go at some of them.

**Comment by nozmajner** [comment]
Issues of point (updated when needed)
#4128 - Stars selected behind buttons
#4115 - UI overlaps

**Comment by Web-eWorks** [comment]
Marked several above issues as completed, given that they were caused by partially-ported oldUI / newUI elements and the affected elements have since been ported to pigui.

I think most of the stretch-goal elements above (e.g. filterable lists, TWR display, etc.) should be moved to a new issue tracking UI Roadmap (2nd pass), as most of the first-pass work has been done and what's present is at the very least at feature parity with newUI.

**Comment by Web-eWorks** [comment]
Moved most open issues to #5319 - leaving only those which have in-flight fix PRs or work branches. Ideally, we'll close this issue with release 2022-02-03.
