### ISSUE TITLE
UI roadmap (2nd pass)

### ISSUE THREAD

**Issue by Web-eWorks** [pioneerspacesim/pioneer#5319]
This issue collects future roadmap goals for the UI beyond the initial implementation or port to PiGui. All developers are welcome to add roadmap goals based on mockups or planned work, but please discuss them on IRC first!

See [the 1st pass project](https://github.com/pioneerspacesim/pioneer/projects/1?fullscreen=true)
[Mockup album.](http://imgur.com/a/6fqrd)
[Old mockups.](https://goo.gl/photos/usbRXT9TECbCPeNi8)

## World View UI
- [ ] Make ship information available as subwindow?
- [ ] Add more information to planetary situation display (bottom right)
- [ ] Comms window for chatting with other ships

#### FlightUI (reticle)
- [ ] Hide option? - (a user asked for it, so it won't be on top of the ship in external view)
- [ ] Follow-target / set speed mode selector
- [ ] Planetary flight / pitch ladder mode?
- [ ] Simplified version for in-cockpit 3d display?
- [ ] Add button/options for autopilot orientation holds

#### Comms Window
- [ ] Display message received timestamps
- [ ] New unread messages count

## Info Screen
- [ ] Convert to tabbed windows in WorldView?
- [ ] Format for use as 3d UI panels in ship cockpits?

#### Mission Display
- [ ] Orderable, filterable list
- [ ] A way to cancel missions

## Station Screen
- [ ] Mass and TWR data available on all screens

#### Bulletin Board System
- [ ] Ordering and filtering
- [ ] Active missions list?
- [ ] Cabin data for passenger missions?
- [ ] Display chat interface in BBS UI instead of popup

#### Commodity Market
- [ ] Ordering and filtering
- [ ] Cargo hold list?
- [ ] Commodity mass-per-unit display

#### Ship Market
- [ ] Compare new ship to current ship

#### Equipment Market
- [ ] Equipment details view (power, heat, etc...)
- [ ] Store purchased / ship equipment at station
- [ ] Equipment loadout presets?
- [ ] Move repair functionality to equipment screen?

## Sector Map
- [ ] Unify layout with [mockups](https://imgur.com/a/YuU79)
- [ ] Alternate star / label coloring (trade price, system economy, etc.)

## System Map
- [ ] Add "local situation" display of current body with planet heightmap, surface bookmarks, range to target, etc
- [ ] Brachistocrone calculator? (deltaV calculator for point-to-point planetary transfer)
- [ ] Improve orbit planner interface
  - [ ] pick point on orbit for new burn
  - [ ] drag handles for delta-V
  - [ ] display total delta-V and burn time in map

## Issues

- [ ] #4142 - always-on FPS counter
- [ ] #4140 - expose default text color / contrast to UI accessibility settings?

**Comment by nozmajner** [comment]
# HUD & UI mockups
@Web-eWorks and @Gliese852: I've moved the useful parts of the [imgur mockup album](https://imgur.com/a/6fqrd) along with some descriptions.

## Landing/Docking Aid Reticule

![image](https://user-images.githubusercontent.com/4182678/202844664-0a6faf07-7fd0-4179-9293-62944492875f.png)
![image](https://user-images.githubusercontent.com/4182678/202844677-4748816b-5268-4926-b4ef-a980247b492a.png)
A reticule docking aid mode. Not sure how it should be activated, but I suspect it could be tied to the landing gear and later to the docking collar extension/collar targeting. For landing all data is displayed relative to the ship. For external docking the display is relative to the active docking port. I suspect in that case it would be useful to tie controls relative to the active docking collar to avoid confusion.
Features:
- **Rotation alignment display:** (at the top-right of the explanation image) A blue cross inside the reticule showing the angle of the ship relative to the landing pad/docking collar. 
   ![image](https://user-images.githubusercontent.com/4182678/202844940-bce529cb-b2e3-4733-9688-80e456061631.png)
   - If it is at the edge of the reticule, it means 45° rotation on the given axis. At the center means the ship aligned to the target. 
   - When rotation is larger than 45°, then a small blue cross indicates at the edge of the reticule indicates its direction.
   - When landing on a landing pad, it indicates pitch and roll alignment
   - When docking to an external docking collar, then it indicates pitch and yaw alignment
   - I think the alignments in degrees could be shown in yellow next to where the orientation indicators are already at, but they aren't really necessary:
   ![image](https://user-images.githubusercontent.com/4182678/202845419-005c5e02-9a96-4f56-a898-b787b2129388.png)
 - **Pad positioin and orientation:** shows the relative position of the landing pad or docking collar. For landing pads, its rotation show yaw alignment, for docking collar it shows roll alignment.
   ![image](https://user-images.githubusercontent.com/4182678/202845006-c976c5b9-23f1-431f-93df-a67b624ed959.png)
   - Size and concentric circles indicate distance to landing pad. Each circle represents 10m (or so) of distance, and ship is at the given distance when the circle is the same size as the reticule circle. When the indicator itself is the same size as the reticule, the ship reached the pad/collar. (calculated from the landing tag)
   - When out of the 45° cone of the reticule, an icon indicates its direction. The icon still shows rotation.
   - The indicator should not be smaller than the icon size when it is at a greater distance.
   - A faint line is projected forward (where the icon also points) to help with orientation.
- **Speed indicator:** visually represents closing speed with a bar. 
   ![image](https://user-images.githubusercontent.com/4182678/202845284-17026d0a-c733-4cd2-a360-57580dddc73c.png)
   - The gauge fills up and down depending on closing speed. (Up and down, so it is visually distinct from the brake distance gauge it replaces in this mode)
   - Only a dot at the center when stationary
   - Fully filled gauge means the upper safe speed
   - It fills up with red from the top and bottom when speed is larger than safety margin
   - Not sure about the safety margin, but my guess would be around 5m/s, and about 20m/s would likely severly damage the collar.
   - There could also be some visual position and speed indicators, but I'm not sure if they worth the clutter (they could look cool though - could be an optional feature, or could be shown in the cockpit on a screen which shows a docking camera)
   ![image](https://user-images.githubusercontent.com/4182678/202845858-c59ba383-f044-4a3d-a891-d1d101df62b0.png)
- The Prograde marker could be a bit smaller, and could be connected with the crosshair with a faint line to aid the position alignment process. (I kinda think that the same could be done to the prograde marker in general as an option)

# Other mockups:
In-flight orbit display with more elaborate comms and contact list: 
![image](https://user-images.githubusercontent.com/4182678/202845963-2869b661-be1c-4a14-b8c8-f692a8e62c7a.png)

### Notification and warning style mockups (also, collapsed contact list):
![image](https://user-images.githubusercontent.com/4182678/202845986-db7aa97b-4187-4681-a4e7-404f5bf4bcda.png)
![image](https://user-images.githubusercontent.com/4182678/202845988-172b14d5-24fe-4ba4-a403-4d8faf9fd9cd.png)

### Atmospheric scooping aid:
![image](https://user-images.githubusercontent.com/4182678/202846055-35acf408-2f0e-40b2-97d2-fccde034bc4e.png)

### Scanning HUD:
![image](https://user-images.githubusercontent.com/4182678/202846123-7fc49faf-1496-469f-a8a5-b62a20324dae.png)

### Orbital map ideas:
![image](https://user-images.githubusercontent.com/4182678/202846165-acb52e47-31ce-40a5-8ed3-a226b552891d.png)
![image](https://user-images.githubusercontent.com/4182678/202846176-f3f18a1c-a06b-46a1-a47c-98a6303a1445.png)

### Ship overview/engineering:
![image](https://user-images.githubusercontent.com/4182678/202846223-644ed662-83da-4f9a-9e5d-566493c20f68.png)
![image](https://user-images.githubusercontent.com/4182678/202846375-76719dce-96e5-44ad-810b-f5a8c0a94c89.png)
![image](https://user-images.githubusercontent.com/4182678/202846379-f436f298-8cd7-49cb-a5cc-d30d2641f71e.png)
![image](https://user-images.githubusercontent.com/4182678/202846383-9db0b547-0bf0-4970-a3a5-305bdd7990cf.png)


### Cargo hold mockups and ideas
Jettison:
![image](https://user-images.githubusercontent.com/4182678/202846105-1704e4aa-e545-45d8-bd3c-14f941872cef.png)
Hidden hold: 
![image](https://user-images.githubusercontent.com/4182678/202846214-b22e20ed-419f-4ea3-a3ab-0e31206ee8c0.png)

**Comment by fluffyfreak** [comment]
🎉❤

**Comment by sturnclaw** [comment]
## Required Icons

CC @bszlrd

Note: with our support for font-based icons, these can either be authored as part of the icons.svg sheet or distributed as a separate ttf font file with glyphs defined in the available subset of the Unicode Private Use Area (U+E000..U+F000). Our icons.svg file is mapped to codepoints U+F000 and following.

- [x] Trash / delete icon (used for jettison as well as editor-context "delete" button)
- [x] General "savefile" icon (see load-game mockup)
- [x] Case-sensitive icon
- [x] "Add" `+` icon (we currently use targeting crosshair for this)
- [x] "Remove" `x` icon (we currently use retrograde indicator for this)
- [x] A reset/undo icon (e.g. left-pointing circle with an arrowhead).
- [ ] "View Selected Object" icon (currently using maneuver node icon)

## Useful Icons

- [x] Save-to-disk icon
- [x] Load-from-disk icon
- [x] Dual arrow major import-export icon for trade computer

## Icon Deduplication

These icons are currently aliased to other icons with separate semantic meanings. Ideally they should receive their own icons with visual clarity.

- [ ] `follow_fill` - Currently aliased to the generic planet icon used to draw interaction dots in the world view. One or the other should be made separate IMO.
- [ ] `equip_fuel_scoop` - Currently using the generic fuel-tank icon; this will become confusing once fuel reservoir equipment is added.
- [ ] `equip_scanner` - Currently aliased to the generic satellite-dish scanner icon. Could be split into planet-scan and ship-scan icons?
- [ ] `ships_no_orbits` - Aliased to the generic ship icon, perhaps could be a variant of the ship-with-orbit-line icon with dashed orbit lines?
- [ ] `filter_ships` - Completely unused at current but will be used to filter out ship contacts in a future iteration of sensor/scanning gameplay.
- [ ] equip_generic - Aliased to the `ecm_advanced` icon; should have its own (clearer) icon.
- [ ] Deploy and pickup (Box w down n out / up n in)
- [ ] Additional generic scanning

**Comment by bszlrd** [comment]
![image](https://github.com/user-attachments/assets/b0a4b3a8-bdb1-427e-979a-ec0a03da8871)
![icons_new_small](https://github.com/user-attachments/assets/a17b6973-8b8d-488f-a4b5-5ad50f85e418)

**Comment by Web-eWorks** [comment]
Semi-copied from IRC: black backgrounds in the icon svg file will render as black in-game - icons need to have fully transparent backgrounds / fills. I'm not sure there's much use for the solid fill increase/decrease icons (as we seem to use solid-fill in only a few cases like the time buttons) and would prefer to normalize around the hollow / stroke-only version of those icons.

I like the current stroke weight for use of the increment / decrement icons at small sizes, but at large sizes the stroke weight is a bit too much. I'd therefore recommend a few icons be saved at their current stroke weight, and the stroke weight be decreased for all of the increment/decrement icons. See the attached infographic for details.

![icon_disposition](https://github.com/user-attachments/assets/9a912334-831a-4109-96dc-7862fa26a381)

**Comment by bszlrd** [comment]
I've used 3px thick lines, about 33% thinner than before. Used the same thickness for the +-x:
![image](https://github.com/user-attachments/assets/528b5690-ab5d-4a85-bb01-3c9f8ad3300b)
[icons_40px_thinner.zip](https://github.com/user-attachments/files/16540563/icons_40px_thinner.zip)

**Comment by Web-eWorks** [comment]
The new icons are good, but a little too thin in my opinion. The old icons are definitely too thick for the overall size, but the new are quite skinny.

New:
![image](https://github.com/user-attachments/assets/addc431a-25a4-4fc4-abb9-b68c24b93e86)
Old:
![image](https://github.com/user-attachments/assets/736c2247-b76f-45f9-9ac6-0aa97f0257b6)


Additionally, the new remove icon is also a little thin in practice - I'd recommend it's stroke weight be increased - possibly to the stroke weight of the "thick" icons as they'll be used on small buttons in practice:

![image](https://github.com/user-attachments/assets/c85994d3-67e8-4b5e-94dd-e40cf8725956)

(The `+` characters in this image are characters from the pionillium font - ideally our icons are a bit thicker to clearly distinguish them from text elements.)

**Comment by bszlrd** [comment]
How about this? Fixed the black stuff too.
[icons_40px.zip](https://github.com/user-attachments/files/16558904/icons_40px.zip)
![image](https://github.com/user-attachments/assets/4dc0f412-6017-47db-bf13-23c473ad7b1d)

**Comment by bszlrd** [comment]
Icons to remove: (from IRC)
![AZHXPgv](https://github.com/user-attachments/assets/f9d1f998-6d0c-4872-b44c-d6f09618fee2)

**Comment by impaktor** [comment]
![356799059-f9d1f998-6d0c-4872-b44c-d6f09618fee2](https://github.com/user-attachments/assets/fa2997ae-a9ec-4ef1-8ef0-df275163b8de)

**Comment by bszlrd** [comment]
![icons_40px](https://github.com/user-attachments/assets/06d65ebb-362c-4097-b7a6-720e7e527461)

**Comment by bszlrd** [comment]
Fixed the Aa Case sensitive icon
![icons_40px](https://github.com/user-attachments/assets/fdf00d21-e4a3-483c-bbbd-68ff90db50db)

**Comment by bszlrd** [comment]
Edited the task list to include a request from the forum, about adding a "center on ship" function to the system map
