### ISSUE TITLE
Tracking: Weapon Refactor

### ISSUE THREAD

**Issue by Web-eWorks** [pioneerspacesim/pioneer#5547]
This is a tracking issue for the ongoing weapon / missile hardpoint refactor as part of the greater Equipment Refactor project. This issue exists to collate **accepted** feature requests and ensure all work items have been completed. There will be a forum post and sister tracking issues covering other aspects of the equipment refactor that will be linked here once created.

### Background

The weapon refactor is an ongoing project to replace the FixedGuns abstraction in Pioneer with a much more flexible weapon system, allowing weapons to be mounted on multiple hardpoints defined on a per-ship basis and provide more tactical depth in weapon selection and equipping.

It has grown to encompass a new hardpoint abstraction to allow displaying weapons on the hull of the ship, as well as providing ship designers with guidelines and templates to ensure that future weapon models will work correctly with all ship models in Pioneer.

The weapon refactor also covers missile gameplay, allowing ships to provide mounting points for individual missiles or racks to mount multiple missiles of the same type both internally and externally. The existing guided/smart/naval missile abstraction will be separated into different size classes of missile with different roles, to provide additional gameplay depth and allow tailoring a combat loadout to a specific mission's role.

### TODO List

- [x] Create GunManager class and port FixedGuns functionality
  - [ ] Limit weapon mounting by hardpoint data
  - [x] Weapon cooling / heat management
  - [ ] Weapon ammunition (loaded/reserve)
- [x] Lua interface to read data from ShipDef hardpoints
- [ ] Ordnance/missile hardpoints
  - [ ] External missile racks
  - [ ] Internal missile racks
  - [ ] Missile rack cooldown / reload delay
- [ ] New missile spawn/launch API
  - [ ] missile instance needs: damage, range, maneuverability, tracking type, etc.
- [ ] Equipment UI to purchase weapons / missiles and mount them to specific hardpoints
- [ ] Ship Market UI overhaul to display weapon/missile hardpoint capacity

### Planned Feature List

- [ ] Enable / disable weapon active state
  - [ ] Master Arm switch for all weapons at once
  - [ ] Select active weapon fire control group / missile station
- [ ] Gimbal / cradle weapon mounts
- [ ] Turret mounts
- [ ] ???

**Comment by nozmajner** [comment]
[Equipment spreadsheet](https://docs.google.com/spreadsheets/d/161XkUPbYW-1mDaPTz2RpSA_zkh5UjD7sEmftJvQPFRU/edit#gid=0)
